# Generated by Django 4.1.1 on 2022-09-17 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desc',
            old_name='title',
            new_name='w_title',
        ),
    ]
