# Generated by Django 4.1.1 on 2022-09-17 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_rename_w_title_desc_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Desc',
            new_name='PageAdmin',
        ),
    ]
