# Generated by Django 4.1.1 on 2022-10-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_rename_desc_pageadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAUTH',
            fields=[
                ('UserID', models.BigAutoField(max_length=15, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('Pass', models.CharField(max_length=80)),
                ('Email/Phone', models.CharField(max_length=35)),
            ],
        ),
    ]
