# Generated by Django 4.1.1 on 2022-10-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_userauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='UserID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
