# Generated by Django 4.1.1 on 2022-10-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20221013_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauth',
            name='EnOFn',
        ),
        migrations.AddField(
            model_name='userauth',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
