# Generated by Django 4.1.1 on 2022-10-14 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_alter_pageadmin_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageadmin',
            options={'verbose_name_plural': 'Page Administrator'},
        ),
    ]
