# Generated by Django 4.1.1 on 2022-12-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_alter_pageadmin_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageadmin',
            old_name='author',
            new_name='tag',
        ),
    ]
