# Generated by Django 4.1.1 on 2023-02-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0013_rename_author_pageadmin_tag"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PageAdmin",
        ),
    ]
